import { expect } from "chai";
import { Board } from "../src/Board.mjs";
import { Tetromino } from '../src/Tetromino.mjs';

describe('Clearing lines', () => {

  it('clears one line at the bottom of the board', () => {
    const board = new Board(null, null,
      `..........
       ..........
       ..........
       ..........
       ..........
       ZZZZ.ZZZZZ`
    );

    board.drop(Tetromino.T_SHAPE);
    for (let i = 0; i < 5; i++) {
      board.tick();
    }

    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ..........
       ..........
       ..........
       ...TTT....`
    );
  });

  it('clears one line at the middle of the board', () => {
    const board = new Board(null, null,
      `..........
       ..........
       ..........
       ..........
       ..........
       ZZZZ.ZZZZZ
       Z.ZZ.ZZ.ZZ
       ZZZZ.ZZZ.Z`
    );

    board.drop(Tetromino.I_SHAPE);
    board.rotateClockwise();
    board.moveLeft();
    for (let i = 0; i < 5; i++) {
      board.tick();
    }

    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ..........
       ..........
       ..........
       ....I.....
       Z.ZZIZZ.ZZ
       ZZZZIZZZ.Z`
    );
  });

  it('clears two lines', () => {
    const board = new Board(null, null,
      `..........
       ..........
       ..........
       ..........
       ..........
       ZZZZ.ZZZZZ
       Z.ZZ.ZZ.ZZ
       ZZZZ.ZZZZZ`
    );

    board.drop(Tetromino.I_SHAPE);
    board.rotateClockwise();
    board.moveLeft();
    for (let i = 0; i < 5; i++) {
      board.tick();
    }

    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ..........
       ..........
       ..........
       ..........
       ....I.....
       Z.ZZIZZ.ZZ`
    );
  });

  it('clears three lines', () => {
    const board = new Board(null, null,
      `..........
       ..........
       ..........
       ..........
       ..........
       ZZZZ.ZZZZZ
       ZZZZ.ZZZZZ
       ZZZZ.ZZZZZ`
    );

    board.drop(Tetromino.I_SHAPE);
    board.rotateClockwise();
    board.moveLeft();
    for (let i = 0; i < 5; i++) {
      board.tick();
    }

    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ..........
       ..........
       ..........
       ..........
       ..........
       ....I.....`
    );
  });

});