import { expect } from "chai";
import { Board } from "../src/Board.mjs";
import { Tetromino } from '../src/Tetromino.mjs';

describe('Clearing lines', () => {

  it('clears one line at the bottom of the board', () => {
    const board = new Board(null, null,
      `..........
       ..........
       ..........
       ..........
       ..........
       ZZZZ.ZZZZZ`
    );

    board.drop(Tetromino.T_SHAPE);
    for (let i = 0; i < 5; i++) {
      board.tick();
    }

    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ..........
       ..........
       ..........
       ...TTT....`
    );
  });

});